name: Flakiness User-Flow Cron - Order Coffee

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  user-flow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2

      - name: NPM CI
        run: npm ci

      - name: User Flow Audit
        run: npx user-flow --ufPath="./user-flows/order-coffee.uf.ts" --url="https://coffee-cart.netlify.app/"

      - name: Compile & CleanUp
        id: compiler
        run: node scripts/compile-and-cleanup.js

      - uses: EndBug/add-and-commit@v7
        with:
          author_name: github-bot
          author_email: opensource@push-based.io
          message: 'Persist Updated Compiled Results'
          add: '*'
